name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install pnpm
      run: npm i pnpm -g
    - name: Install dependencies
      run: pnpm install
    - name: Test
      run: pnpm test
